--- #YAML:1.0
name:                Util-SQLiteDB-UniSchema
version:             v0.01
abstract:            Interface to a single-schema SQLite DB
license:             perl
author:              
    - Kan Liu <kan@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
